// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0zTHVMxk-LLzdSt0dJ-KBzMTVTQPJino',
    appId: '1:649606330097:web:6cfb6444467adcc6cf9b50',
    messagingSenderId: '649606330097',
    projectId: 'todo-list-85e8d',
    authDomain: 'todo-list-85e8d.firebaseapp.com',
    storageBucket: 'todo-list-85e8d.appspot.com',
    measurementId: 'G-YV01GRBS6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLR5eNaBMMmiR8nH4sJlh9uEulyovDgqs',
    appId: '1:649606330097:android:700fa2d143d1df68cf9b50',
    messagingSenderId: '649606330097',
    projectId: 'todo-list-85e8d',
    storageBucket: 'todo-list-85e8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgNslWtGN_IkCv2CgrCktbcHeUTGDFYQk',
    appId: '1:649606330097:ios:58bbee1966de9283cf9b50',
    messagingSenderId: '649606330097',
    projectId: 'todo-list-85e8d',
    storageBucket: 'todo-list-85e8d.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgNslWtGN_IkCv2CgrCktbcHeUTGDFYQk',
    appId: '1:649606330097:ios:4d59ac1c41a405e8cf9b50',
    messagingSenderId: '649606330097',
    projectId: 'todo-list-85e8d',
    storageBucket: 'todo-list-85e8d.appspot.com',
    iosBundleId: 'com.example.toDoList.RunnerTests',
  );
}
